workflows:
  engine-sync-universal:
    name: Build Engine Sync Mac Universal
    instance_type: mac_mini_m1
    
    scripts:
      - name: Instalar dependencias do Python
        script: |
          pip3 install pyinstaller customtkinter Pillow requests tinytag
          
      - name: Compilar App Mac Universal
        script: |
          # pyinstaller configurado para embutir o icone .icns e a imagem .png na raiz do app (.)
          pyinstaller --noconsole --onefile --target-architecture universal2 --icon=sync_icon.icns --add-data "logo_engine.png:." engine_sync_app.py
          
      - name: Compactar o App em ZIP
        script: |
          cd dist
          zip -r EngineSync_MacUniversal.zip engine_sync_app.app
          
    artifacts:
      - dist/EngineSync_MacUniversal.zip
