name: Build Mac Universal App

on: [push]

jobs:
  build:
    name: Build Mac Universal (Intel & M-Series)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Mantido 3.9 para garantir compatibilidade com os Macs de 2012

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tinytag customtkinter Pillow

      - name: Build with PyInstaller
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.13" # Instrui o compilador a funcionar do macOS High Sierra para frente
        run: |
          pyinstaller --noconsole --onefile \
            --target-architecture universal2 \
            --icon=sync_icon.icns \
            --add-data "logo_engine.png:." \
            engine_sync_app.py
          
          # Renomeia o arquivo gerado para identificar que é a versão definitiva
          mv dist/engine_sync_app dist/EngineSync_Mac_Universal

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EngineSync_Mac_Universal
          path: dist/EngineSync_Mac_Universal
